server:
  port: 8081

#loggin:
#  level:
#    org.hibernate.engine.jdbc.env.internal.LobCreatrorBuilderImpl: ERROR
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_project?currentSchema=demo_schema
    username: postgres
    password: postgres
  security:
    user:
      password: password
      name: user